

[sensor_temperatura]
temperatura_min_normal = 15
temperatura_max_normal = 23
temperatura_min_outlier = 10
temperatura_max_outlier = 28
temperatura_probabilidad_outlier = 0.05
temperatura_media_dist_normal = 20
temperatura_desviacion_estandar = 1
temperatura_outlier_activados = true

[sensor_humedad]
humedad_min_normal = 0
humedad_max_normal = 100
humedad_media_dist_normal = 60
humedad_desviacion_estandar = 1
humedad_outlier_desactivados = true